"""Add books table

Revision ID: 377594978900
Revises: 
Create Date: 2024-07-06 21:52:18.720032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377594978900'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('authors', sa.String(length=200), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=False),
    sa.Column('published_date', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('main_category', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
